### ISSUE TITLE
Terra focused cw template

### ISSUE THREAD

**Issue by 0xFable** [terra-money/templates#1]
In the past I worked on a rust cw template that was very similar to the official one but much slimmer and targeted to 0.16.0 of cosmwasm which is compatible with Terra col 5. 
Is this project worth adding here? https://github.com/0xFable/cw-minimal-template
It is just a smart contract template no web app included

**Comment by iamssen** [comment]
Please update the templates.json file and register the PR. The new template is always welcome. This template appears to be two months before the last modification. Please check if the execution is normal before registration.
